'use strict';
const crypto=require('crypto'), VERSION='execution-parity-2.0.0', EPS=1e-12;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const id=(p,s)=>`${p}_${crypto.createHash('sha256').update(String(s)).digest('hex').slice(0,20)}`;
function geometry(side,entry,sl,tp){side=String(side||'').toUpperCase();entry=n(entry,NaN);sl=n(sl,NaN);tp=n(tp,NaN);if(!['BUY','SELL'].includes(side)||![entry,sl,tp].every(x=>Number.isFinite(x)&&x>0))return{ok:false,reason:'NON_FINITE_OR_NON_POSITIVE_GEOMETRY'};return(side==='BUY'?sl<entry&&entry<tp:tp<entry&&entry<sl)?{ok:true}:{ok:false,reason:'STALE_OR_INVERTED_GEOMETRY'};}
function roundDown(v,step){step=n(step);if(!(step>0))return n(v);const d=Math.min(12,Math.max(0,(String(step).split('.')[1]||'').length));return Number((Math.floor((n(v)+step*1e-9)/step)*step).toFixed(d));}
function validateQuantity(qty,price,f={},budget=Infinity){const q=roundDown(qty,f.qtyStep),notional=Number((q*n(price)).toFixed(12));if(!(q>0))return{ok:false,reason:'INVALID_QTY'};if(n(f.minOrderQty)&&q<n(f.minOrderQty))return{ok:false,reason:'MIN_QTY'};if(n(f.maxOrderQty)&&q>n(f.maxOrderQty))return{ok:false,reason:'MAX_QTY'};if(n(f.minNotionalValue)&&notional<n(f.minNotionalValue))return{ok:false,reason:'MIN_NOTIONAL'};if(Number.isFinite(budget)&&notional>budget+EPS)return{ok:false,reason:'BUDGET_EXCEEDED'};return{ok:true,qty:q,notional};}
function createIntent(s,at,o={}){const entry=n(s.plannedEntry,n(s.entry,NaN)),intent={version:VERSION,intentId:id('intent',`${s.id}|${at}`),signalId:s.id,symbol:s.sym||s.symbol,side:String(s.side||'').toUpperCase(),plannedEntry:entry,sl:n(s.sl),tp:n(s.tp1),orderType:String(o.orderType||'LIMIT').toUpperCase(),tif:o.tif||'GTC',requestedQty:n(o.qty,n(s.qty)),createdAt:n(at),status:'CREATED',reason:null};const deny=o.eligibility&&o.eligibility.wouldPlace===false?o.eligibility.reason:null;if(o.missedMove){intent.status='WITHHELD';intent.reason='MISSED_MOVE_LIVE_PARITY';return intent;}if(deny){intent.status='WITHHELD';intent.reason=deny;return intent;}if(!o.hadFirstTouch&&o.requireRetest!==false){intent.status='WITHHELD';intent.reason='NO_GENUINE_RETEST';return intent;}const g=geometry(intent.side,entry,intent.sl,intent.tp);if(!g.ok){intent.status='REJECTED';intent.reason=g.reason;return intent;}if(!(intent.requestedQty>0)){intent.status='REJECTED';intent.reason='INVALID_QTY';return intent;}intent.status='ACCEPTED';intent.acceptedAt=n(o.acceptedAt,at);return intent;}
function appendEvent(t,type,at,fields={}){t.executionEvents=Array.isArray(t.executionEvents)?t.executionEvents:[];const seq=t.executionEvents.length+1,e=Object.freeze({seq,eventId:id('evt',`${t.id||t.signalId}|${type}|${at}|${seq}`),type,at:n(at),...fields});t.executionEvents.push(e);return e;}
function newPosition(intent){return{id:intent.signalId,intent,plannedEntry:intent.plannedEntry,avgFillPrice:null,filledQty:0,remainingQty:0,closedQty:0,entryFees:0,exitFees:0,funding:0,realizedGross:0,realizedPnl:null,openedAt:null,status:intent.status==='ACCEPTED'?'PENDING_ACK':'NO_ORDER',cancelState:'NONE',seenExecIds:{},bracketVersions:[{version:1,sl:intent.sl,tp:intent.tp,requestedAt:intent.createdAt,effectiveAt:null}],executionEvents:[]};}
function acknowledgeOrder(p,a={}){if(!p||p.intent.status!=='ACCEPTED')throw Error('ACK_WITHOUT_ACCEPTED_INTENT');if(['CLOSED','CANCELLED'].includes(p.status))throw Error('ACK_TERMINAL_POSITION');const at=n(a.at);if(at<n(p.intent.acceptedAt))throw Error('ACK_BEFORE_INTENT');p.acknowledgedAt=at;p.status='PENDING_FILL';if(p.bracketVersions[0]&&!p.bracketVersions[0].effectiveAt)p.bracketVersions[0].effectiveAt=at;appendEvent(p,'ORDER_ACK',at,{orderId:a.orderId||null});return p;}
function requestCancel(p,at){if(!p||['CLOSED','CANCELLED'].includes(p.status))throw Error('CANCEL_TERMINAL_POSITION');if(p.cancelState!=='NONE'&&p.cancelState!=='REJECTED')return p;p.cancelState='REQUESTED';appendEvent(p,'CANCEL_REQUESTED',at,{});return p;}
function acknowledgeCancel(p,at,result='ACKNOWLEDGED'){if(p.cancelState!=='REQUESTED')throw Error('CANCEL_ACK_WITHOUT_REQUEST');if(result==='REJECTED'){p.cancelState='REJECTED';appendEvent(p,'CANCEL_REJECTED',at,{});return p;}p.cancelState='ACKNOWLEDGED';p.status=p.remainingQty<=EPS?'CANCELLED':'OPEN';appendEvent(p,'CANCEL_ACK',at,{remainingOpenQty:p.remainingQty});return p;}
function applyFill(p,f){if(!p||!p.intent||p.intent.status!=='ACCEPTED')throw Error('FILL_WITHOUT_ACCEPTED_INTENT');if(['CLOSED','CANCELLED'].includes(p.status)||p.cancelState==='ACKNOWLEDGED')throw Error('FILL_TERMINAL_POSITION');const qty=n(f.qty),px=n(f.price),at=n(f.at),execId=String(f.execId||id('simexec',`${p.intent.intentId}|${at}|${qty}|${px}`));if(p.seenExecIds[execId])return p;if(!(qty>0&&px>0&&at>=n(p.acknowledgedAt,p.intent.acceptedAt)))throw Error('INVALID_FILL');if(p.intent.orderType==='LIMIT'&&((p.intent.side==='BUY'&&px>p.intent.plannedEntry+EPS)||(p.intent.side==='SELL'&&px<p.intent.plannedEntry-EPS)))throw Error('LIMIT_PRICE_VIOLATION');if(n(p.filledQty)+qty>n(p.intent.requestedQty)+EPS)throw Error('OVERFILL');const g=geometry(p.intent.side,px,p.intent.sl,p.intent.tp);if(!g.ok)throw Error(`POST_FILL_${g.reason}`);const old=n(p.filledQty),total=old+qty;p.avgFillPrice=((old*n(p.avgFillPrice))+qty*px)/total;p.filledQty=total;p.remainingQty=n(p.remainingQty)+qty;p.openedAt=p.openedAt==null?at:Math.min(p.openedAt,at);p.status='OPEN';p.entryFees+=n(f.fee);p.seenExecIds[execId]=1;appendEvent(p,'FILL',at,{execId,price:px,qty,fee:n(f.fee),liquidity:f.liquidity||'UNKNOWN'});return p;}
function amendBracket(p,a){if(!p||['CLOSED','CANCELLED'].includes(p.status))throw Error('AMEND_TERMINAL_POSITION');const prior=p.bracketVersions[p.bracketVersions.length-1],next={version:prior.version+1,sl:n(a.sl,prior.sl),tp:n(a.tp,prior.tp),requestedAt:n(a.requestedAt),effectiveAt:a.effectiveAt==null?null:n(a.effectiveAt)};if(next.effectiveAt!=null&&next.effectiveAt<next.requestedAt)throw Error('AMENDMENT_EFFECTIVE_BEFORE_REQUEST');p.bracketVersions.push(next);appendEvent(p,'BRACKET_AMENDMENT',next.requestedAt,next);return next;}
function bracketAt(p,at){return p.bracketVersions.filter(b=>b.effectiveAt!=null&&b.effectiveAt<=at).sort((a,b)=>a.effectiveAt-b.effectiveAt).pop()||null;}
function closeFill(p,price,qty,at,c={}){if(!p||p.status!=='OPEN')throw Error('CLOSE_WITHOUT_OPEN_POSITION');at=n(at);if(at<n(p.openedAt)||at<n(p.lastExitAt,-Infinity))throw Error('EXIT_BEFORE_ENTRY');qty=n(qty);if(!(qty>0)||qty>n(p.remainingQty)+EPS)throw Error('INVALID_CLOSE_QTY');price=n(price);if(!(price>0))throw Error('INVALID_CLOSE_PRICE');const gross=(p.intent.side==='BUY'?price-p.avgFillPrice:p.avgFillPrice-price)*qty;p.realizedGross+=gross;p.remainingQty=Math.max(0,p.remainingQty-qty);p.closedQty+=qty;p.exitFees+=n(c.fee);p.funding+=n(c.funding);p.realizedPnl=p.realizedGross-p.entryFees-p.exitFees+p.funding;p.lastExitAt=at;if(p.remainingQty<=EPS)p.status='CLOSED';appendEvent(p,'EXIT_FILL',at,{execId:c.execId||null,price,qty,fee:n(c.fee),funding:n(c.funding),gross,net:p.realizedPnl});return p;}
function ambiguity(p,start,end,reason){(p.ambiguities||(p.ambiguities=[])).push({startAt:start,endAt:end,reason});p.lastProcessedThrough=Math.max(n(p.lastProcessedThrough,-Infinity),end);}
function processMarketEvents(p,events,o={}){if(!p||p.status!=='OPEN'||!(p.remainingQty>0))return null;const sorted=[...(events||[])].sort((a,b)=>n(a.startAt,a.at)-n(b.startAt,b.at)||n(a.seq)-n(b.seq));for(const e of sorted){const start=n(e.startAt,e.at),end=n(e.endAt,e.at);if(end<=n(p.openedAt)||end<=n(p.lastProcessedThrough,-Infinity))continue;if(e.type==='CANDLE'&&start<p.openedAt&&end>p.openedAt){ambiguity(p,start,end,'ENTRY_OVERLAPPING_CANDLE');continue;}const amends=p.bracketVersions.filter(b=>b.version>1&&b.effectiveAt!=null&&b.effectiveAt>start&&b.effectiveAt<end);if(e.type==='CANDLE'&&amends.length){ambiguity(p,start,end,'BRACKET_AMENDMENT_INSIDE_CANDLE');continue;}const at=e.type==='CANDLE'?end:n(e.at),b=bracketAt(p,at);if(!b){p.lastProcessedThrough=Math.max(n(p.lastProcessedThrough,-Infinity),end);continue;}let high,low;if(e.type==='CANDLE'){high=n(e.high,NaN);low=n(e.low,NaN);}else high=low=n(e.price,NaN);if(![high,low].every(Number.isFinite))continue;const buy=p.intent.side==='BUY',tpHit=buy?high>=b.tp:low<=b.tp,slHit=buy?low<=b.sl:high>=b.sl;p.lastProcessedThrough=Math.max(n(p.lastProcessedThrough,-Infinity),end);if(!tpHit&&!slHit)continue;const stop=slHit,outcome=stop?'SL_HIT':'TP_HIT';let executable=stop?(Number.isFinite(n(e.executablePrice,NaN))?n(e.executablePrice):e.type==='QUOTE'?n(e.price):b.sl):b.tp;if(stop&&e.type==='CANDLE'){const open=n(e.open,NaN);if(Number.isFinite(open))executable=buy?Math.min(b.sl,open):Math.max(b.sl,open);}const bp=n(stop?o.stopSlippageBp:o.tpSlippageBp),exitPrice=buy?executable*(1-bp/10000):executable*(1+bp/10000),funding=typeof o.fundingAt==='function'?n(o.fundingAt(at,p)):n(o.funding);closeFill(p,exitPrice,p.remainingQty,at,{fee:n(o.exitFeeRate)*p.remainingQty*exitPrice,funding});return{outcome,at,exitPrice,bracketVersion:b.version,ambiguous:tpHit&&slHit};}return null;}
function normalizeExecutionEvent(raw={},source='UNKNOWN'){const type=String(raw.type||raw.execType||raw.event||'').toUpperCase(),side=String(raw.side||'').toUpperCase();return Object.freeze({source:String(source).toUpperCase(),type:type==='TRADE'?'FILL':type,execId:String(raw.execId||raw.exec_id||raw.executionId||raw.id||''),orderId:String(raw.orderId||raw.order_id||''),side:['BUY','SELL'].includes(side)?side:null,price:n(raw.price??raw.execPrice,NaN),qty:n(raw.qty??raw.execQty,NaN),fee:n(raw.fee??raw.execFee),funding:n(raw.funding),at:n(raw.at??raw.execTime??raw.timestamp),liquidity:raw.liquidity||(raw.isMaker===true?'MAKER':raw.isMaker===false?'TAKER':'UNKNOWN')});}
function consumeExecutionEvent(p,event){const e=normalizeExecutionEvent(event,event.source||'NORMALIZED');if(e.type==='ORDER_ACK')return acknowledgeOrder(p,e);if(e.type==='FILL')return applyFill(p,e);if(e.type==='CANCEL_REQUESTED')return requestCancel(p,e.at);if(e.type==='CANCEL_ACK')return acknowledgeCancel(p,e.at);if(e.type==='EXIT_FILL')return closeFill(p,e.price,e.qty,e.at,e);throw Error(`UNSUPPORTED_EXECUTION_EVENT_${e.type}`);}
module.exports={VERSION,geometry,validateQuantity,createIntent,newPosition,acknowledgeOrder,requestCancel,acknowledgeCancel,applyFill,amendBracket,bracketAt,closeFill,processMarketEvents,appendEvent,normalizeExecutionEvent,consumeExecutionEvent};
